// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Zsb3ccPpCFmZ8maT-qYM3pQZWxFgu8',
    appId: '1:887893975050:web:a171f208e44d5e06377ff3',
    messagingSenderId: '887893975050',
    projectId: 'forumdatabase-d9f2d',
    authDomain: 'forumdatabase-d9f2d.firebaseapp.com',
    storageBucket: 'forumdatabase-d9f2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxwljvrM0Pl0pWL6HLVbnqt4BNA_mcJmo',
    appId: '1:887893975050:android:b9feef1aa4d0672c377ff3',
    messagingSenderId: '887893975050',
    projectId: 'forumdatabase-d9f2d',
    storageBucket: 'forumdatabase-d9f2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt8ErPbiiHHHv3RIhhTaJYP87pt77xEa4',
    appId: '1:887893975050:ios:56d285605ed6a825377ff3',
    messagingSenderId: '887893975050',
    projectId: 'forumdatabase-d9f2d',
    storageBucket: 'forumdatabase-d9f2d.firebasestorage.app',
    iosBundleId: 'edu.tarc.my.assignmentProject',
  );
}
